// generated by pronto from the layout this app is built in — do not edit

package chess

loop: surface: sources: pronto: "../../plugins/pronto"
build: meta: dir: "apps/chess"
cluster: meta: root: "../../"
cluster: meta: runtime: "../../"
