// generated by pronto from the cel: constraints in program.cue — do not edit
//
// `checks` are the SQL CHECK bodies emit.cue renders into the table DDL;
// `seed` carries what each field-level cel says about the field's own
// value, which is what vets a stated row; `enums` lists the values a
// closed constraint admits, for the readers that cannot enumerate a CUE
// disjunction, and `bounds` states what an open one admits — a range, a
// length, a pattern — for the readers that have to propose a value.
// An invariant binds `this` to the ROW, and a predicate over
// several columns constrains no single field's value, so it derives a
// CHECK body and nothing for CUE.
package chess

import "strings"

code: state: entities: {
	Game: {
		seed: [...{
			id?: strings.MaxRunes(64)
			mode?: ("house" | "hotseat")
			bot?: ("nell" | "otto" | "vera" | "magnus" | "sable")
			level?: ("2" | "3" | "4" | "5")
			bot_name?: strings.MinRunes(1)
			bot_line?: strings.MinRunes(1)
			set?: ("print" | "staunton" | "engraved" | "disc")
			tc?: ("unlimited" | "1+0" | "3+2" | "5+0" | "10+0")
			side?: ("white" | "black")
			board?: strings.MinRunes(64) & strings.MaxRunes(64) & =~ "^(?:\\.|[PNBRQKpnbrqk]){64}$"
			castling?: =~ "^K?Q?k?q?$"
			ep?: =~ "^([a-h][36])?$"
			halfmove?: >=0 & <=150
			fullmove?: >=1 & <=9999
			fen?: strings.MinRunes(20) & strings.MaxRunes(100)
			turn?: ("white" | "black")
			ply?: >=0
			status?: ("playing" | "over")
			result?: ("" | "1-0" | "0-1" | "1/2-1/2")
			won?: strings.MaxRunes(16)
			termination?: ("" | "checkmate" | "stalemate" | "threefold" | "fifty-move" | "insufficient" | "resignation" | "flag" | "agreement")
			check?: ("yes" | "no")
			selected?: strings.MaxRunes(2)
			flipped?: ("yes" | "no")
			dragged?: ("yes" | "no")
			last_from?: strings.MaxRunes(2)
			last_to?: strings.MaxRunes(2)
			current?: ("yes" | "no")
			ordinal?: strings.MinRunes(4) & strings.MaxRunes(4)
			last_tick?: >=0
			cursor?: strings.MaxRunes(72)
			step?: ("" | "first" | "back" | "fwd" | "live")
			caret?: strings.MinRunes(2) & strings.MaxRunes(2)
			caret_go?: ("" | "up" | "down" | "left" | "right" | "row-start" | "row-end" | "first" | "last")
			promo_from?: strings.MaxRunes(2)
			promo_to?: strings.MaxRunes(2)
			promo_f?: strings.MinRunes(1) & strings.MaxRunes(1)
			promo_r?: strings.MinRunes(1) & strings.MaxRunes(1)
			draw_offer?: ("none" | "you" | "declined")
			eco?: strings.MaxRunes(3)
			opening?: strings.MaxRunes(48)
			taken_white?: strings.MaxRunes(32)
			taken_black?: strings.MaxRunes(32)
			edge?: >=-39 & <=39
			reviewing?: ("yes" | "no")
			pgn?: strings.MaxRunes(2000)
			ask?: strings.MaxRunes(100)
			ask_ply?: strings.MaxRunes(4)
			ask_nodes?: strings.MaxRunes(8)
			ask_lines?: ("" | "1" | "2")
			review?: ("" | "reading" | "read")
			review_line?: strings.MaxRunes(64)
			acc_low?: strings.MaxRunes(3)
			acc_top?: strings.MaxRunes(3)
			tally_low?: strings.MaxRunes(64)
			tally_top?: strings.MaxRunes(64)
			bar?: strings.MaxRunes(2)
			bar_label?: strings.MaxRunes(8)
			note_head?: strings.MaxRunes(24)
			note_mark?: ("" | "book" | "!" | "?!" | "?" | "??")
			note?: strings.MaxRunes(280)
			hint?: strings.MaxRunes(24)
			seat_top_name?: strings.MinRunes(1)
			seat_top_line?: strings.MinRunes(1)
			seat_top_ini?: strings.MinRunes(1) & strings.MaxRunes(1)
			seat_top_taken?: strings.MaxRunes(32)
			seat_top_edge?: strings.MaxRunes(3)
			seat_top_turn?: ("yes" | "no")
			seat_top_low?: ("yes" | "no")
			seat_low_name?: strings.MinRunes(1)
			seat_low_line?: strings.MinRunes(1)
			seat_low_ini?: strings.MinRunes(1) & strings.MaxRunes(1)
			seat_low_taken?: strings.MaxRunes(32)
			seat_low_edge?: strings.MaxRunes(3)
			seat_low_turn?: ("yes" | "no")
			seat_low_low?: ("yes" | "no")
			seat_top_elo?: strings.MaxRunes(8)
			seat_low_elo?: strings.MaxRunes(8)
		}]
		enums: {
			mode: ["house","hotseat"]
			bot: ["nell","otto","vera","magnus","sable"]
			level: ["2","3","4","5"]
			set: ["print","staunton","engraved","disc"]
			tc: ["unlimited","1+0","3+2","5+0","10+0"]
			side: ["white","black"]
			turn: ["white","black"]
			status: ["playing","over"]
			result: ["","1-0","0-1","1/2-1/2"]
			termination: ["","checkmate","stalemate","threefold","fifty-move","insufficient","resignation","flag","agreement"]
			check: ["yes","no"]
			flipped: ["yes","no"]
			dragged: ["yes","no"]
			current: ["yes","no"]
			step: ["","first","back","fwd","live"]
			caret_go: ["","up","down","left","right","row-start","row-end","first","last"]
			draw_offer: ["none","you","declined"]
			reviewing: ["yes","no"]
			ask_lines: ["","1","2"]
			review: ["","reading","read"]
			note_mark: ["","book","!","?!","?","??"]
			seat_top_turn: ["yes","no"]
			seat_top_low: ["yes","no"]
			seat_low_turn: ["yes","no"]
			seat_low_low: ["yes","no"]
		}
		bounds: {
			id: {sizeMax: 64}
			bot_name: {sizeMin: 1}
			bot_line: {sizeMin: 1}
			board: {sizeMin: 64, sizeMax: 64, regex: "^(?:\\.|[PNBRQKpnbrqk]){64}$"}
			castling: {regex: "^K?Q?k?q?$"}
			ep: {regex: "^([a-h][36])?$"}
			halfmove: {intMin: 0, intMax: 150}
			fullmove: {intMin: 1, intMax: 9999}
			fen: {sizeMin: 20, sizeMax: 100}
			ply: {intMin: 0}
			won: {sizeMax: 16}
			selected: {sizeMax: 2}
			last_from: {sizeMax: 2}
			last_to: {sizeMax: 2}
			ordinal: {sizeMin: 4, sizeMax: 4}
			last_tick: {intMin: 0}
			cursor: {sizeMax: 72}
			caret: {sizeMin: 2, sizeMax: 2}
			promo_from: {sizeMax: 2}
			promo_to: {sizeMax: 2}
			promo_f: {sizeMin: 1, sizeMax: 1}
			promo_r: {sizeMin: 1, sizeMax: 1}
			eco: {sizeMax: 3}
			opening: {sizeMax: 48}
			taken_white: {sizeMax: 32}
			taken_black: {sizeMax: 32}
			edge: {intMin: -39, intMax: 39}
			pgn: {sizeMax: 2000}
			ask: {sizeMax: 100}
			ask_ply: {sizeMax: 4}
			ask_nodes: {sizeMax: 8}
			review_line: {sizeMax: 64}
			acc_low: {sizeMax: 3}
			acc_top: {sizeMax: 3}
			tally_low: {sizeMax: 64}
			tally_top: {sizeMax: 64}
			bar: {sizeMax: 2}
			bar_label: {sizeMax: 8}
			note_head: {sizeMax: 24}
			note: {sizeMax: 280}
			hint: {sizeMax: 24}
			seat_top_name: {sizeMin: 1}
			seat_top_line: {sizeMin: 1}
			seat_top_ini: {sizeMin: 1, sizeMax: 1}
			seat_top_taken: {sizeMax: 32}
			seat_top_edge: {sizeMax: 3}
			seat_low_name: {sizeMin: 1}
			seat_low_line: {sizeMin: 1}
			seat_low_ini: {sizeMin: 1, sizeMax: 1}
			seat_low_taken: {sizeMax: 32}
			seat_low_edge: {sizeMax: 3}
			seat_top_elo: {sizeMax: 8}
			seat_low_elo: {sizeMax: 8}
		}
	}
	Setup: {
		seed: [...{
			id?: ("next")
			mode?: ("house" | "hotseat")
			bot?: ("nell" | "otto" | "vera" | "magnus" | "sable")
			level?: ("2" | "3" | "4" | "5")
			tc?: ("unlimited" | "1+0" | "3+2" | "5+0" | "10+0")
			side?: ("white" | "black")
		}]
		enums: {
			id: ["next"]
			mode: ["house","hotseat"]
			bot: ["nell","otto","vera","magnus","sable"]
			level: ["2","3","4","5"]
			tc: ["unlimited","1+0","3+2","5+0","10+0"]
			side: ["white","black"]
		}
	}
	Move: {
		seed: [...{
			id?: strings.MaxRunes(72)
			game_id?: strings.MaxRunes(64)
			ply?: >=1
			number?: >=1
			color?: ("white" | "black")
			san?: strings.MinRunes(2) & strings.MaxRunes(8)
			uci?: strings.MinRunes(4) & strings.MaxRunes(5)
			board_after?: strings.MinRunes(64) & strings.MaxRunes(64) & =~ "^(?:\\.|[PNBRQKpnbrqk]){64}$"
			turn_after?: ("white" | "black")
			castling_after?: =~ "^K?Q?k?q?$"
			ep_after?: =~ "^([a-h][36])?$"
			halfmove_after?: >=0 & <=150
			fullmove_after?: >=1 & <=9999
			fen_after?: strings.MinRunes(20) & strings.MaxRunes(100)
			capture?: ("yes" | "no")
			check?: ("yes" | "no")
			retracted?: ("yes" | "no")
			before?: strings.MaxRunes(7)
			second?: strings.MaxRunes(7)
			best?: strings.MaxRunes(8)
			line?: strings.MaxRunes(48)
			after?: strings.MaxRunes(7)
			mark?: ("" | "book" | "!" | "?!" | "?" | "??")
			tide?: strings.MaxRunes(2)
		}]
		enums: {
			color: ["white","black"]
			turn_after: ["white","black"]
			capture: ["yes","no"]
			check: ["yes","no"]
			retracted: ["yes","no"]
			mark: ["","book","!","?!","?","??"]
		}
		bounds: {
			id: {sizeMax: 72}
			game_id: {sizeMax: 64}
			ply: {intMin: 1}
			number: {intMin: 1}
			san: {sizeMin: 2, sizeMax: 8}
			uci: {sizeMin: 4, sizeMax: 5}
			board_after: {sizeMin: 64, sizeMax: 64, regex: "^(?:\\.|[PNBRQKpnbrqk]){64}$"}
			castling_after: {regex: "^K?Q?k?q?$"}
			ep_after: {regex: "^([a-h][36])?$"}
			halfmove_after: {intMin: 0, intMax: 150}
			fullmove_after: {intMin: 1, intMax: 9999}
			fen_after: {sizeMin: 20, sizeMax: 100}
			before: {sizeMax: 7}
			second: {sizeMax: 7}
			best: {sizeMax: 8}
			line: {sizeMax: 48}
			after: {sizeMax: 7}
			tide: {sizeMax: 2}
		}
	}
	Square: {
		seed: [...{
			id?: strings.MinRunes(2) & strings.MaxRunes(2)
			ord?: strings.MinRunes(2) & strings.MaxRunes(2)
			label?: strings.MinRunes(8) & strings.MaxRunes(24)
			shade?: ("light" | "dark")
			piece?: strings.MaxRunes(1)
			glyph?: strings.MaxRunes(1)
			color?: ("" | "white" | "black")
			selected?: ("yes" | "no")
			target?: ("yes" | "no")
			capture?: ("yes" | "no")
			last?: ("yes" | "no")
			check?: ("yes" | "no")
			drag?: ("yes" | "no")
			drag_from?: strings.MaxRunes(2)
			coord_file?: strings.MaxRunes(1)
			coord_rank?: strings.MaxRunes(1)
		}]
		enums: {
			shade: ["light","dark"]
			color: ["","white","black"]
			selected: ["yes","no"]
			target: ["yes","no"]
			capture: ["yes","no"]
			last: ["yes","no"]
			check: ["yes","no"]
			drag: ["yes","no"]
		}
		bounds: {
			id: {sizeMin: 2, sizeMax: 2}
			ord: {sizeMin: 2, sizeMax: 2}
			label: {sizeMin: 8, sizeMax: 24}
			piece: {sizeMax: 1}
			glyph: {sizeMax: 1}
			drag_from: {sizeMax: 2}
			coord_file: {sizeMax: 1}
			coord_rank: {sizeMax: 1}
		}
	}
	Piece: {
		seed: [...{
			id?: strings.MinRunes(4) & strings.MaxRunes(4)
			piece?: strings.MinRunes(1) & strings.MaxRunes(1)
			color?: ("white" | "black")
			symbol?: strings.MaxRunes(24)
			initial?: strings.MinRunes(1) & strings.MaxRunes(1)
			glyph?: strings.MaxRunes(2)
			square?: strings.MinRunes(2) & strings.MaxRunes(2)
			file?: >=0 & <=7
			rank?: >=0 & <=7
			taken?: ("yes" | "no")
			lit?: ("yes" | "no")
		}]
		enums: {
			color: ["white","black"]
			taken: ["yes","no"]
			lit: ["yes","no"]
		}
		bounds: {
			id: {sizeMin: 4, sizeMax: 4}
			piece: {sizeMin: 1, sizeMax: 1}
			symbol: {sizeMax: 24}
			initial: {sizeMin: 1, sizeMax: 1}
			glyph: {sizeMax: 2}
			square: {sizeMin: 2, sizeMax: 2}
			file: {intMin: 0, intMax: 7}
			rank: {intMin: 0, intMax: 7}
		}
	}
	Legal: {
		seed: [...{
			id?: strings.MaxRunes(72)
			game_id?: strings.MaxRunes(64)
			ply?: >=0
			from_sq?: strings.MinRunes(2) & strings.MaxRunes(2)
			to_sq?: strings.MinRunes(2) & strings.MaxRunes(2)
			uci?: strings.MinRunes(4) & strings.MaxRunes(5)
			san?: strings.MinRunes(2) & strings.MaxRunes(8)
			promo?: ("" | "Q" | "R" | "B" | "N")
			board_after?: strings.MinRunes(64) & strings.MaxRunes(64) & =~ "^(?:\\.|[PNBRQKpnbrqk]){64}$"
			turn_after?: ("white" | "black")
			castling_after?: =~ "^K?Q?k?q?$"
			ep_after?: =~ "^([a-h][36])?$"
			halfmove_after?: >=0 & <=150
			fullmove_after?: >=1 & <=9999
			fen_after?: strings.MinRunes(20) & strings.MaxRunes(100)
			capture?: ("yes" | "no")
			check?: ("yes" | "no")
			mate?: ("yes" | "no")
		}]
		enums: {
			promo: ["","Q","R","B","N"]
			turn_after: ["white","black"]
			capture: ["yes","no"]
			check: ["yes","no"]
			mate: ["yes","no"]
		}
		bounds: {
			id: {sizeMax: 72}
			game_id: {sizeMax: 64}
			ply: {intMin: 0}
			from_sq: {sizeMin: 2, sizeMax: 2}
			to_sq: {sizeMin: 2, sizeMax: 2}
			uci: {sizeMin: 4, sizeMax: 5}
			san: {sizeMin: 2, sizeMax: 8}
			board_after: {sizeMin: 64, sizeMax: 64, regex: "^(?:\\.|[PNBRQKpnbrqk]){64}$"}
			castling_after: {regex: "^K?Q?k?q?$"}
			ep_after: {regex: "^([a-h][36])?$"}
			halfmove_after: {intMin: 0, intMax: 150}
			fullmove_after: {intMin: 1, intMax: 9999}
			fen_after: {sizeMin: 20, sizeMax: 100}
		}
	}
	Tick: {
		seed: [...{
			id?: strings.MaxRunes(8)
			n?: >=0
			beat?: ("on")
		}]
		enums: {
			beat: ["on"]
		}
		bounds: {
			id: {sizeMax: 8}
			n: {intMin: 0}
		}
	}
	Opening: {
		seed: [...{
			id?: strings.MinRunes(3) & strings.MaxRunes(3)
			name?: strings.MinRunes(1)
			uci?: strings.MinRunes(1)
		}]
		bounds: {
			id: {sizeMin: 3, sizeMax: 3}
			name: {sizeMin: 1}
			uci: {sizeMin: 1}
		}
	}
}
